chap_3_blog_extending/mysite/blog/urls.py
from django.conf.urls import url
from . import views

#Feeds
from .feeds import LatestPostsFeed



urlpatterns = [
    # post views
    url(r'^$', views.post_list, name='post_list'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
    #url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
        views.post_detail,
        name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
    url(r'^feed/$', LatestPostsFeed(), name='post_feed')
]

chap_3_blog_extending/mysite/mysite/urls.py
from django.conf.urls import patterns, include, url

#Sitemap
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
        'posts': PostSitemap,
        }


from django.contrib import admin
admin.autodiscover()



urlpatterns =[ 
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

chap_3_blog_extending/mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

#taggit
from taggit.managers import TaggableManager
'''
#Command in the  shell to create Blog ' Post

import random
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from faker import Factory
fake = Factory.create()
s = ' '

user = User.objects.first()
for item in range(1,40):
    author = fake.name()
    title = s.join(fake.words(random.randint(4,16)))
    slug = slugify(title)
    #slugify the title
    status = 'published'
    body = s.join(fake.paragraphs(random.randint(2,10)))
    book = Post.objects.create(title=title, author=user, status=status, body=body, slug=slug )
    print(author)
    book.save()
    #Creating Tags
    #Retrieve the last saved Post
    p = Post.objects.first() #last saved Post
    available_tags = ['music', 'tango', 'hip hop', 'country', 'jazz']
    for i in range(0, random.randint(0,5)):
        pick_a_tag = random.choice(available_tags)
        if pick_a_tag not in p.tags.all():
            p.tags.add(pick_a_tag)        
    #creating Comments
    for sug in range(1,3):
        name = fake.name()
        email = fake.email()
        body = s.join(fake.paragraphs(random.randint(1,3)))
        comment = Comment.objects.create(post=p, name=name, email=email, body=body)
        comment.save()

####
#Delete Post and comments
comments = Comment.objects.all()
for i in comments:
    i.delete()

posts = Post.objects.all()
for i in posts:
    i.delete()
'''

# Create your models here.

class PublishedManager(models.Manager):

    def get_queryset(self):
        return super(PublishedManager, self).get_queryset()\
                .filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
            ('draft', 'Draft'),
            ('published', 'Published'),
            )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date="publish")
    author = models.ForeignKey(User, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default="draft")
    tags = TaggableManager()

    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()


    class Meta:
        ordering = ('-publish', )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, 
            self.publish.strftime('%m'),
            self.publish.strftime('%d'),
            self.slug])



class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

chap_3_blog_extending/mysite/blog/forms.py
from django import forms
from . models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

chap_3_blog_extending/mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
#Taggit
from taggit.models import Tag
from django.db.models import Count

def post_list(request, tag_slug=None):
    """

    """
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page,
                                                   'posts': posts,
                                                   'tag':tag})


class PostListView(ListView):
    """

    """
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_detail(request, year, month, day, post):
    """

    """
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    #list of active comments for this post
    comments = post.comments.filter(active=True)

    if request.method == 'POST':
        #A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            #Created Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags',
                                                                             '-publish')[:4]
    return  render(request, 'blog/post/detail.html', {'post': post,
                                                     'comments': comments,
                                                     'comment_form': comment_form,
                                                     'similar_posts': similar_posts})




def post_share(request, post_id):
    """

    """
    #Retrieve the post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        #Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            #Form fields passed validation
            cd = form.cleaned_data
            # .... send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            #send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post':post, 'form': form, 'sent': sent})

chap_3_blog_extending/mysite/blog/templates/blog/base.html
{% load blog_tags %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/blog.css' %}">
</head>
<body>
  
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>

  <div id="sidebar">
    <h2>My blog</h2>
    <p>This is my blog. I've written {% total_posts %} post so far.</p>
    <p><a href="{% url 'blog:post_feed' %}">Subscribe to my RSS feed</a></p>
    <p><a href="http://localhost:8002/sitemap.xml">View the Sitemap</a></p>

    <h3>Latest posts</h3>
     {% show_latest_posts %}

      <hr>
     <h3>Most commented posts</h3>
     {% get_most_commented_posts as most_commented_posts %}
     <ul>
       {% for post in most_commented_posts %}
         <li>
             <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
         </li>
       {% endfor %}
     </ul>

      <hr>
     <h3>Less commented posts</h3>
     {% get_less_commented_posts as less_commented_posts %}
     <ul>
       {% for post in less_commented_posts %}
         <li>
             <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
         </li>
       {% endfor %}
     </ul>

  </div>

</body>
</html>

chap_3_blog_extending/mysite/blog/templates/blog/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
           <a href="?page={{page.previous_page_number}}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

chap_3_blog_extending/mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
    {{ post.body|markdown }}

    <p>
      <a href="{% url 'blog:post_share' post.id %}">Share this post</a>
    </p>

    <h2>Similar posts</h2>
    {% for post in similar_posts %}
        <p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
    {% empty %}
        There are no similar posts yet.
    {% endfor %}

    {% with comments.count as total_comments %}
        <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}</p>
            {{ comment.body|markdown }}
        </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}

    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {%  endif %}




{% endblock %}

chap_3_blog_extending/mysite/blog/templates/blog/post/latest_posts.html
<ul>
	{% for post in latest_posts %}
		<li> 
				<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
		</li>
	{% endfor %}
</ul>

chap_3_blog_extending/mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title  %}My blog{% endblock %}
{% block content %}

  {% include "pagination.html" with page=posts %}

  <h1>My Blog</h1>

  {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
  {% endif %}

  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </h2>
        <p class="tags">
            Tags: 
            {% for tag in post.tags.all %}
                <a href="{% url "blog:post_list_by_tag" tag.slug %}">{{ tag.name }}</a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>

    <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|truncatewords:30|markdown }}
    <p class="tags">Tags: {{ post.tags.all|join:", " }}</p>

  {% endfor %}
{% endblock %}

chap_3_blog_extending/mysite/blog/templates/blog/post/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
           <a href="?page={{page.previous_page_number}}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

chap_3_blog_extending/mysite/blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %} Share a post {% endblock %}

{% block content %}
  {% if sent %}
     <h1>E-mail successfully sent</h1>
     <p>
         "{{ post.title }}" was successfully sent to {{cd.to}}.
     </p>
  {% else %}
      <h1>Share "{{ post.title}}" by e-mail</h1>
      <form action="." method='post'> 
        {{ form.as_p}}
        {% csrf_token %}
        <input type="submit" value="send e-mmail"}/>
      </form>
  {% endif %}
{% endblock  %}